### ISSUE TITLE
Add options

### ISSUE THREAD

**Issue by jbblanchet** [SteveSanderson/knockout-es5#25]
Right now the second parameter is a list the properties to observe. I think this should instead be an option object, so we can add more features easily without breaking compatibility. Sample features that could be added are recursion (see #24), properties to exclude instead of to include, custom property filter function (for example to exclude all properties beginning by _ or $), and plenty of other way better ideas.

**Comment by unsafecode** [comment]
+1

**Comment by archangel-irk** [comment]
Since 0.2.0-alpha added options `deep` and `fields`.
