### ISSUE TITLE
Using with browserify

### ISSUE THREAD

**Issue by hugozap** [SteveSanderson/knockout-es5#31]
Hi,  i tried to use the plugin with browserify (with  npm install knockout-es5 ) . But ran into issues with weakmap and ko dependencies.  I did some small changes to make it work with browserify in case someone needs it:

https://gist.github.com/hugozap/1fdbd93094809cc7c691

**Comment by archangel-irk** [comment]
Thank you very much. On the days I will look in detail.

**Comment by hugozap** [comment]
The problem i found was with the way it detects commonjs and the fact that browserify does not support conditional requires. I had to move the requires to the top, and instead of including WeakMap, just include a require("weakmap") ( This breaks AMD support )

This is a temp fix ( works only with commonjs )  and requires knockout and weakmap dependencies, i think that an optimal solution would be to publish a browserify ready package to npm so it would be easy just to require("knockout-es5-browserify"), i can help if needed.

**Comment by archangel-irk** [comment]
I understand if you are not difficult, you can make a Pull Request with the changes, and I'll accept. Thank you.

**Comment by archangel-irk** [comment]
Hi, I'm back. Tell us please what you want using knockout-es5 and browserify.

Please write an example of what you want and what you get with the original knockout-es5. Maybe I can solve your problem or suggest how it can be solved.
