### ISSUE TITLE
Add latest to NPM?

### ISSUE THREAD

**Issue by grofit** [SteveSanderson/knockout-es5#41]
Any chance we could get the latest version of this added to NPM, the latest on there is 0.1.1.

**Comment by archangel-irk** [comment]
I can't do it. I hope that @SteveSanderson will help us.

**Comment by atom-project** [comment]
+1

**Comment by mmacaula** [comment]
+1

**Comment by archangel-irk** [comment]
I contacted the owner of the npm repo and asked to update the version of the library

**Comment by grofit** [comment]
one other thing worth mentioning is that currently there is an issue where ideally this lib should be using peerDependencies to satisfy the knockout dependency as shown here;

https://github.com/Knockout-Contrib/Knockout-Validation/issues/602

I have changed it in a fork and can submit a pull request if you want, but its a 1 line change.

**Comment by archangel-irk** [comment]
Thanks, its done.
