### ISSUE TITLE
Breaks F12 Tools in IE11

### ISSUE THREAD

**Issue by Manuel-S** [SteveSanderson/knockout-es5#58]
Hi,

when having imported knockout-es5 globally, the F12 debugger breaks when you type variables in the console.
It throws an exception of 

> Invalid caller object 

on line 562:

    if ('toString' in coercedObj && coercedObj.toString() === '[object Window]') {

the variable `coercedObj` contains a `WindowPrototype` and throws on the `toString()` call.

**Comment by archangel-irk** [comment]
Hi, this PR is merged https://github.com/SteveSanderson/knockout-es5/pull/57

**Comment by Manuel-S** [comment]
It works. Thanks!
